# One control plane (runs the controller) and four "GPU" workers.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    labels: {nvidia.com/gpu.present: "true"}
  - role: worker
    labels: {nvidia.com/gpu.present: "true"}
  - role: worker
    labels: {nvidia.com/gpu.present: "true"}
  - role: worker
    labels: {nvidia.com/gpu.present: "true"}
